# Generated by Django 2.2.7 on 2019-12-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('bookTitle', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('bookImage', models.ImageField(upload_to='')),
                ('bookLink', models.CharField(max_length=100)),
                ('LinkTitle', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('readtext', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
