# Generated by Django 2.2.7 on 2019-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedbook',
            name='LinkTitle',
            field=models.CharField(max_length=1000),
        ),
    ]
