# Generated by Django 2.2.7 on 2019-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191216_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedbook',
            name='LinkTitle',
            field=models.TextField(),
        ),
    ]
