# Generated by Django 2.2.7 on 2019-12-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20191216_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedbook',
            name='LinkTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='bookLink',
            field=models.CharField(max_length=1000),
        ),
    ]
