# Generated by Django 2.2.7 on 2019-12-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20191216_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendedbook',
            old_name='readtext',
            new_name='good',
        ),
    ]
