# Generated by Django 2.2.7 on 2019-12-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20191218_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedbook',
            name='goodtext',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
