# Generated by Django 2.2.7 on 2019-12-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20191218_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedbook',
            name='LinkTitle',
        ),
        migrations.RemoveField(
            model_name='recommendedbook',
            name='bookLink',
        ),
    ]
