# Generated by Django 2.2.7 on 2019-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20191218_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedbook',
            name='notGood',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recommendedbook',
            name='notGoodtext',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
