# Generated by Django 2.2.7 on 2019-12-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_comment_subcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='target',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='SubComment',
        ),
    ]
