# Generated by Django 2.2.7 on 2019-12-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20191219_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='名無し', max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.RecommendedBook')),
            ],
        ),
    ]
