# Generated by Django 2.2.7 on 2019-12-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='handlename',
        ),
    ]
